name: Deploy to DigitalOcean

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: "registry.digitalocean.com/reflex-github"  # change accordingly!
  IMAGE_NAME: "demo-app" # change accordingly!

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v3

    - name: Build container image latest version
      run: |
        docker build \
          --build-arg YOUR_SECERET1=${{ secrets.YOUR_SECERET1 }} \  # in case you have any Secrets you need to pass through
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Slim down the container image
      uses: kitabisa/docker-slim-action@v1
      env:
        DSLIM_HTTP_PROBE: false
      with:
        target: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        tag: ${{ github.sha }}-slim

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-slim

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.3
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.DO_HOST }}
          username: ghactions
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          envs: REGISTRY,IMAGE_NAME,GITHUB_SHA
          script: |
            echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | docker login $REGISTRY -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --password-stdin
            docker pull $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
            docker stop $IMAGE_NAME || true
            docker rm $IMAGE_NAME || true
            docker run -d --restart always -e API_URL=http://host.docker.internal:8000 -p 80:8080 --name $IMAGE_NAME $REGISTRY/$IMAGE_NAME:$GITHUB_SHA

  clean-registry:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Remove tag to save space
        run: doctl registry repository delete-tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} ${{ github.sha }} -f
